version: '3.8'

volumes:
  node-cache:
  pnpm-cache:

services:
  app:
    build:
      args:
        - BASE_IMAGE=node:16
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - '3000:3000'
      - '3001:3001'
      - '6006:6006'
    volumes:
      - .:/app
      - node-cache:/root/.cache
      - pnpm-cache:/root/.pnpm-store
