name: 'setup-node-with-pnpm'
description: 'Sets up node with pnpm and installs playwright based on necessity'
inputs:
  use-hoisted:
    description: 'Determine whether to install with --shamefully-hoist or not'
    required: false
    default: false
  use-playwright:
    description: 'Determine whether to install playwright or not'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Checkout 🛎
      uses: actions/checkout@v3
    - name: Enable corepack
      run: corepack enable
      shell: bash
    - name: Install dependencies with pnpm
      if: ${{ inputs.use-hoisted != 'true' }}
      run: pnpm install
      shell: bash
    - name: Install dependencies with pnpm --shamefully-hoist
      if: ${{ inputs.use-hoisted == 'true' }}
      run: pnpm install --shamefully-hoist
      shell: bash
    - name: Install playwright
      if: ${{ inputs.use-playwright == 'true' }}
      run: |
        apt-get update
        pnpx playwright install --with-deps chromium
      shell: bash
