version: '3.8'

volumes:
  playwright:

services:
  app:
    build:
      args:
        - BASE_IMAGE=mcr.microsoft.com/playwright:focal
      context: ./
      dockerfile: ./integration/Dockerfile.playwright
    command: 'pnpm ci:test'
    stdin_open: true
    tty: true
    environment:
      - DISPLAY
    working_dir: /app
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./:/app
      - playwright:/ms-playwright
