name: Deploy app and storybook to GitHub pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare node and pnpm
        uses: ./.github/actions/setup-node-with-pnpm.yml
        with:
          use-hoisted: true

      - name: Building page and storybook 🔧
        run: |
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build/
